import PDFDocument from 'pdfkit';

import type { PayslipLine } from './payslip-breakdown';

type PdfDoc = InstanceType<typeof PDFDocument>;

function pdfBuffer(docInit: (doc: PdfDoc) => void): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 48 });
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    try {
      docInit(doc);
      doc.end();
    } catch (e) {
      reject(e);
    }
  });
}

function inr(n: number): string {
  return `₹${n.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

export function renderEmployeePayslipPdf(opts: {
  companyName: string;
  periodLabel: string;
  employeeName: string;
  employeeCode: string;
  dateOfJoining: string;
  designation: string | null;
  department: string | null;
  grade: string | null;
  pan: string | null;
  bankAccount: string | null;
  ifsc: string | null;
  earnings: PayslipLine[];
  deductions: PayslipLine[];
  gross: number;
  deductionsTotal: number;
  net: number;
}): Promise<Buffer> {
  return pdfBuffer((doc) => {
    doc.fontSize(16).fillColor('#0f172a').text('Payslip', { align: 'center' });
    doc.moveDown(0.25);
    doc.fontSize(10).fillColor('#64748b').text(opts.companyName || 'Employer', { align: 'center' });
    doc.moveDown(0.75);
    doc.fontSize(11).fillColor('#0f172a').text(`Pay period: ${opts.periodLabel}`);
    doc.moveDown(0.6);

    doc.fontSize(9).fillColor('#334155');
    doc.text(`Name: ${opts.employeeName}`);
    doc.text(`Employee no.: ${opts.employeeCode}`);
    doc.text(`Joining date: ${opts.dateOfJoining}`);
    if (opts.designation) doc.text(`Designation: ${opts.designation}`);
    if (opts.department) doc.text(`Department: ${opts.department}`);
    if (opts.grade) doc.text(`Grade: ${opts.grade}`);
    if (opts.pan) doc.text(`PAN: ${opts.pan}`);
    if (opts.bankAccount) doc.text(`Bank account: ${opts.bankAccount}`);
    if (opts.ifsc) doc.text(`IFSC: ${opts.ifsc}`);
    doc.moveDown();

    const leftX = 48;
    const midX = 210;
    const wCol = 220;
    const yStart = doc.y;

    doc.fontSize(10).fillColor('#1e40af').text('Earnings', leftX, yStart, { width: wCol });
    doc.text('Amount (₹)', leftX + 130, yStart, { width: 80, align: 'right' });
    let y = yStart + 16;
    doc.fontSize(9).fillColor('#0f172a');
    for (const row of opts.earnings) {
      doc.text(row.label, leftX, y, { width: 120 });
      doc.text(inr(row.amount), leftX + 120, y, { width: 90, align: 'right' });
      y += 14;
    }
    doc.fontSize(9).fillColor('#0f172a');
    doc.text('Total', leftX, y, { underline: true, width: 120 });
    doc.text(inr(opts.gross), leftX + 120, y, { width: 90, align: 'right' });
    const earningsEndY = y + 18;

    y = yStart;
    doc.fontSize(10).fillColor('#1e40af').text('Deductions', midX, y, { width: wCol });
    doc.text('Amount (₹)', midX + 130, y, { width: 80, align: 'right' });
    y += 16;
    doc.fontSize(9).fillColor('#0f172a');
    for (const row of opts.deductions) {
      doc.text(row.label, midX, y, { width: 120 });
      doc.text(inr(row.amount), midX + 120, y, { width: 90, align: 'right' });
      y += 14;
    }
    doc.text('Total', midX, y, { underline: true, width: 120 });
    doc.text(inr(opts.deductionsTotal), midX + 120, y, { width: 90, align: 'right' });
    const deductionsEndY = y + 18;

    doc.y = Math.max(earningsEndY, deductionsEndY);
    doc.moveDown(1.2);
    doc.fontSize(12).fillColor('#15803d');
    doc.text(`Net pay for ${opts.periodLabel}: ${inr(opts.net)}`, { align: 'center' });
    doc.moveDown(2);
    doc.fontSize(7).fillColor('#94a3b8').text('Generated by Vetan — employee payslip', {
      align: 'center',
    });
  });
}
