import PDFDocument from 'pdfkit';

type PdfDoc = InstanceType<typeof PDFDocument>;

function pdfBuffer(docInit: (doc: PdfDoc) => void): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 48 });
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    try {
      docInit(doc);
      doc.end();
    } catch (e) {
      reject(e);
    }
  });
}

export function renderSubscriptionInvoicePdf(opts: {
  tenantName: string;
  tenantSlug: string;
  invoiceId: string;
  periodLabel: string;
  amountInr: number;
  currency: string;
  status: string;
  paidAt: string | null;
}): Promise<Buffer> {
  return pdfBuffer((doc) => {
    doc.fontSize(18).text('Vetan — Subscription invoice', { align: 'center' });
    doc.moveDown(0.75);
    doc.fontSize(10).fillColor('#333333');
    doc.text(`Workspace: ${opts.tenantName} (${opts.tenantSlug})`);
    doc.text(`Invoice ID: ${opts.invoiceId}`);
    doc.text(`Billing period: ${opts.periodLabel}`);
    doc.text(`Status: ${opts.status}`);
    if (opts.paidAt) {
      doc.text(`Paid on: ${opts.paidAt}`);
    }
    doc.moveDown();
    doc.fillColor('#111111').fontSize(11);
    doc.text(
      `Line item: Vetan subscription (${opts.periodLabel}) — ${opts.currency} ${opts.amountInr.toLocaleString('en-IN')}`,
    );
    doc.moveDown(0.5);
    doc.fontSize(12).text(`Total due: ${opts.currency} ${opts.amountInr.toLocaleString('en-IN')}`, {
      align: 'right',
    });
    doc.moveDown(2);
    doc
      .fontSize(8)
      .fillColor('#666666')
      .text('Generated by Vetan. SaaS subscription billing record.', { align: 'center' });
  });
}

export function renderPayrollPaymentPdf(opts: {
  tenantName: string;
  tenantSlug: string;
  payrollRunId: string;
  periodLabel: string;
  status: string;
  employeeCount: number;
  grossInr: number;
  deductionsInr: number;
  netInr: number;
  lines: { code: string; name: string; gross: number; deductions: number; net: number }[];
}): Promise<Buffer> {
  const maxRows = 100;
  const rows = opts.lines.slice(0, maxRows);
  const more = opts.lines.length - rows.length;

  return pdfBuffer((doc) => {
    doc.fontSize(18).text('Vetan — Payroll payment summary', { align: 'center' });
    doc.moveDown(0.75);
    doc.fontSize(10).fillColor('#333333');
    doc.text(`Workspace: ${opts.tenantName} (${opts.tenantSlug})`);
    doc.text(`Payroll run ID: ${opts.payrollRunId}`);
    doc.text(`Pay period: ${opts.periodLabel}`);
    doc.text(`Run status: ${opts.status}`);
    doc.text(`Employees included: ${opts.employeeCount}`);
    doc.moveDown();
    doc.fontSize(11).fillColor('#111111');
    doc.text(`Total gross:        INR ${opts.grossInr.toLocaleString('en-IN')}`);
    doc.text(`Total deductions:   INR ${opts.deductionsInr.toLocaleString('en-IN')}`);
    doc.fontSize(12).text(`Total net payroll: INR ${opts.netInr.toLocaleString('en-IN')}`);
    doc.moveDown();

    doc.fontSize(10).fillColor('#111111').text('Per-employee net pay', { underline: true });
    doc.moveDown(0.35);
    doc.fontSize(8).fillColor('#444444');
    for (const r of rows) {
      const line = `${r.code}  ${r.name}  |  gross ${r.gross.toLocaleString('en-IN')}  ded ${r.deductions.toLocaleString('en-IN')}  net ${r.net.toLocaleString('en-IN')}`;
      doc.text(line, { width: doc.page.width - 96 });
    }

    if (more > 0) {
      doc.moveDown(0.35);
      doc.fontSize(9).fillColor('#666666').text(`… and ${more} more employee(s). Totals above include the full run.`);
    }

    doc.moveDown(2);
    doc
      .fontSize(8)
      .fillColor('#666666')
      .text(
        'Generated by Vetan. Amounts reflect the payroll run registered in your workspace.',
        { align: 'center' },
      );
  });
}
